user-image-dir = D:/gabri/Documents/IFSP/5_semestre/SPOPIE1/projetoextensao/.gource/avatars
title = Projeto de Extensão – Evolução do Código
auto-skip-seconds = 0.5
initial-pause = 2
camera-mode = track
bloom-multiplier = 1.1
bloom-intensity = 0.15
hide = mouse
highlight-users = true
highlight-dirs = true
dir-name-depth = 4
viewport = 1920x1080
user-color = Gabriella Mendes:5F78FF
user-color = Matheus Victor:FF8A5C
user-color = Matheus Fogaça:9F75D6
user-color = Isabelle Severino:6EC88F
user-color = Gustavo Almeida:F7C66F
logo = .gource/logo.png
logo-position = topright
logo-opacity = 230
logo-size = 150
