user-image-dir = .gource/avatars
title = Projeto de Extensão – Evolução do Código
initial-pause = 2
camera-mode = track
bloom-multiplier = 1.1
bloom-intensity = 0.15
hide = mouse
highlight-users = true
highlight-dirs = true
dir-name-depth = 4
viewport = 1920x1080
user-color = Gabriella Mendes:5F78FF
user-color = Matheus Victor:FF8A5C
user-color = Matheus Fogaca:9F75D6
user-color = Isabelle Severino:6EC88F
user-color = Gustavo Almeida:F7C66F
logo = .gource/logo.png
logo-position = topright
logo-opacity = 230
logo-size = 150
seconds-per-day = 0.25
time-scale = 2.0
auto-skip-seconds = 1.0
stop-at-end = true
file-idle-time = 0
max-file-lag = 0.3